server:
  port: 8081
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.100.38:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://192.168.100.39:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
# 打印sql
logging:
  level:
    com.smallren : debug
#1.加载MyBatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smallren.entity
